### ISSUE TITLE
Commit 248 (bbbccbf) build succeeds, tests fail with several errors

### ISSUE THREAD

**Issue by fusion809** [MustaphaTR/Romanovs-Vengeance#9] opened 2019-01-17 14:53 UTC
Hi,

It seems that on Arch Linux and NixOS unstable, commit 248 (bbbccbfb577867f2c9c07fa6a315f453ffb63727) tests are failing, here is the full log from running `make test`: https://gist.github.com/9f2742a8b70741d9b5475de991580729. `make` runs fine, to be precise this is the output of running `make`:

```bash
make[1]: Entering directory '/data/GitHub/others/Romanovs-Vengeance/engine'
Fetching StyleCopPlus from NuGet
Fetching StyleCop files from NuGet
Fetching ICSharpCode.SharpZipLib from NuGet
Fetching MaxMind.Db from NuGet
Fetching SharpFont from NuGet
Fetching NUnit from NuGet
Fetching NUnit.Console from NuGet
Fetching Open.Nat from NuGet
Fetching FuzzyLogicLibrary from NuGet.
Fetching SDL2-CS from GitHub.
Fetching OpenAL-CS from GitHub.
Fetching Eluant from GitHub.
Fetching rix0rrr.BeaconLib from NuGet.
Updating GeoIP country database from MaxMind.
Detected Lua 5.1 library at /lib/liblua.so.5.1.5
Eluant.dll.config has been created successfully.
CSC fixheader.exe
CSC OpenRA.Game.exe
CSC OpenRA.Platforms.Default.dll
CSC mods/common/OpenRA.Mods.Common.dll
CSC mods/common/OpenRA.Mods.Cnc.dll
CSC mods/d2k/OpenRA.Mods.D2k.dll
CSC mods/as/OpenRA.Mods.AS.dll
CSC OpenRA.Utility.exe
CSC OpenRA.Server.exe
make[1]: Leaving directory '/data/GitHub/others/Romanovs-Vengeance/engine'
/data/GitHub/others/Romanovs-Vengeance/OpenRA.Mods.RA2.sln:  warning : Don't know how to handle GlobalSection ExtensibilityGlobals, Ignoring.
The mod logic has been built.
```

Thanks for your time,
Brenton

**Comment by MustaphaTR** [comment] 2019-01-17 18:05
We haven't really checked the make test much. I'm aware that it give a lot of warnings and some errors, but didn't get to fix them.

**Comment by GraionDilach** [comment] 2019-01-17 18:46
https://github.com/MustaphaTR/Romanovs-Vengeance/blob/da295c75e1a9768af63c3c737858ca3a340677f6/OpenRA.Mods.RA2.sln#L43-L48 was added by you(r tool) during OpenRA->AS shift which is the cause of this issue. I've never seen these lines elsewhere.

**Comment by MustaphaTR** [comment] 2019-03-17 13:07
This should be fixed now as i removed the thing Graion shows and Travis is set up and is passing.

**Closed by MustaphaTR** 2019-03-17 13:07 UTC
