### ISSUE TITLE
MacOS - Game content not found

### ISSUE THREAD

**Issue by eranb** [MustaphaTR/Romanovs-Vengeance#39] opened 2019-08-27 17:40 UTC
After mounting both ISO files ( Allies and Soviets ) it fails to detects the drives and install the content.
When trying to install the content from the regular OpenRA Red Alert everything works as expected and it manage to detect and install the content.
You've any idea what I'm missing ?

Thanks

**Comment by MustaphaTR** [comment] 2019-08-28 18:16
Mod is currently not set up to detect the Yuri's Revenge content from the discs. Only from Origin installments. I don't know much about the installer code so i couldn't do it, we have been manually copying the files ourselves, but it is not really possible on Mac since you can't install the originals there.

If you have a Windows PC which you can install the game, you are gonna need at least, `ra2.mix`, `ra2md.mix`, `language.mix` and `langmd.mix` in your ra2 content folder. Additionally `theme.mix` and `thememd.mix` has music and the whole `taunts` folder contain taunts.

Closing as a duplicate of #18.

**Closed by MustaphaTR** 2019-08-28 18:16 UTC

**Comment by eranb** [comment] 2019-08-29 19:33
@MustaphaTR Thanks
