### ISSUE TITLE
Game Crash - eabe6e3

### ISSUE THREAD

**Issue by Bond007s** [MustaphaTR/Romanovs-Vengeance#50] opened 2020-07-31 05:11 UTC
[Logs.zip](https://github.com/MustaphaTR/Romanovs-Vengeance/files/5005196/Logs.zip)
Unsure this is helpful. I was playing a game on skirmish and it crashed. Here is my log... I updated my build earlier today to test for the crash that was fixed with the level 5 powers... I think they were fixed... Unsure where and how to reproduce. I will look at reproducing this maybe this weekend...

Platform is Windows
Engine version is eabe6e3
Using SDL 2 with OpenGL (Modern) renderer
Desktop resolution: 1920x1080
No custom resolution provided, using desktop resolution
Using resolution: 1920x1080
Using window scale 1.50
OpenGL version: 3.2.0 - Build 25.20.100.6617
Using default sound device
Internal mods:
        rv: Red Alert 2: Romanov's Vengeance (eabe6e3)
        all: All mods (eabe6e3)
        cnc: Tiberian Dawn (eabe6e3)
        d2k: Dune 2000 (eabe6e3)
        modcontent: Mod Content Manager (eabe6e3)
        ra: Red Alert (eabe6e3)
        ts: Tiberian Sun (eabe6e3)
External mods:
        cnc-playtest-20190825: Tiberian Dawn (playtest-20190825)
        cnc-playtest-20200329: Tiberian Dawn (playtest-20200329)
        cnc-release-20200503: Tiberian Dawn (release-20200503)
        d2k-playtest-20190825: Dune 2000 (playtest-20190825)
        d2k-playtest-20200329: Dune 2000 (playtest-20200329)
        d2k-release-20200503: Dune 2000 (release-20200503)
        ra-playtest-20190825: Red Alert (playtest-20190825)
        ra-playtest-20200329: Red Alert (playtest-20200329)
        ra-release-20200503: Red Alert (release-20200503)
        sp-release-20200210: Shattered Paradise (release-20200210)
        cnc-{DEV_VERSION}: Tiberian Dawn ({DEV_VERSION})
        cnc3-{DEV_VERSION}: Tiberian War ({DEV_VERSION})
        d2k-playtest-20200303: Dune 2000 (playtest-20200303)
        ra-playtest-20200303: Red Alert (playtest-20200303)
        ra-{DEV_VERSION}: Red Alert ({DEV_VERSION})
        ra2-{DEV_VERSION}: Red Alert 2 ({DEV_VERSION})
        ra3-{DEV_VERSION}: Red Alert 3 ({DEV_VERSION})
        rast-cac2997: Red Alert: Space Trek (cac2997)
        rv-cac2997: Star Trek: Red Alert (cac2997)
        rv-eabe6e3: Red Alert 2: Romanov's Vengeance (eabe6e3)
        sa-5037495acf92653db30ccdf9cbaa27b45e8786d2: Swarm Assault (5037495acf92653db30ccdf9cbaa27b45e8786d2)
        sp-release-20200114: Shattered Paradise (release-20200114)
        ss-551ab2f: Sole Survivor (551ab2f)
        ts-{DEV_VERSION}: Tiberian Sun ({DEV_VERSION})
        yr-release-20200202: Red Alert 2 Yuri's Revenge (release-20200202)
        ra-playtest-20191021: Red Alert (playtest-20191021)
Loading mod: rv
Medium - GL Debug API Output: Performance - API_ID_RECOMPILE_FRAGMENT_SHADER performance warning has been generated. Fragment shader recompiled due to state change.
   at OpenRA.Platforms.Default.OpenGL.BuildErrorText(Int32 source, Int32 type, Int32 severity, StringBuilder message)
   at OpenRA.Platforms.Default.OpenGL.DebugMessageHandler(Int32 source, Int32 type, UInt32 id, Int32 severity, Int32 length, StringBuilder message, IntPtr userparam)
   at OpenRA.Platforms.Default.Sdl2GraphicsContext.DrawPrimitives(PrimitiveType pt, Int32 firstVertex, Int32 numVertices)
   at OpenRA.Renderer.DrawBatch[T](IVertexBuffer`1 vertices, Int32 firstVertex, Int32 numVertices, PrimitiveType type)
   at OpenRA.Graphics.SpriteRenderer.Flush()
   at OpenRA.Renderer.EndFrame(IInputHandler inputHandler)
   at OpenRA.Mods.Common.LoadScreens.SheetLoadScreen.Display()
   at OpenRA.ModData..ctor(Manifest mod, InstalledMods mods, Boolean useLoadScreen)
   at OpenRA.Game.InitializeMod(String mod, Arguments args)
   at OpenRA.Game.Initialize(Arguments args)
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.Program.Main(String[] args)

[2020-07-30T22:16:20] Game started
AL lib: (EE) ALCmmdevPlayback_mixerProc: WaitForSingleObjectEx error: 0x102
[2020-07-30T22:53:46] Game started
Exception of type `System.InvalidOperationException`: Attempting to query the position of an invalid Target
   at OpenRA.Traits.Target.get_CenterPosition() in C:\Users\Public\Desktop\Games\Romanovs-Vengeance-master\game\engine\OpenRA.Game\Traits\Target.cs:line 172
   at OpenRA.Mods.AS.Warheads.FireShrapnelWarhead.<>c__DisplayClass9_3.<DoImpact>b__5() in C:\Users\Public\Desktop\Games\Romanovs-Vengeance-master\game\engine\OpenRA.Mods.AS\Warheads\FireShrapnelWarhead.cs:line 132
   at OpenRA.Mods.Common.Projectiles.LaserZap.Tick(World world) in C:\Users\Public\Desktop\Games\Romanovs-Vengeance-master\game\engine\OpenRA.Mods.Common\Projectiles\LaserZap.cs:line 171
   at OpenRA.WorldUtils.DoTimed[T](IEnumerable`1 e, Action`1 a, String text) in C:\Users\Public\Desktop\Games\Romanovs-Vengeance-master\game\engine\OpenRA.Game\WorldUtils.cs:line 79
   at OpenRA.World.Tick() in C:\Users\Public\Desktop\Games\Romanovs-Vengeance-master\game\engine\OpenRA.Game\World.cs:line 468
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in C:\Users\Public\Desktop\Games\Romanovs-Vengeance-master\game\engine\OpenRA.Game\Game.cs:line 605
   at OpenRA.Game.LogicTick() in C:\Users\Public\Desktop\Games\Romanovs-Vengeance-master\game\engine\OpenRA.Game\Game.cs:line 631
   at OpenRA.Game.Loop() in C:\Users\Public\Desktop\Games\Romanovs-Vengeance-master\game\engine\OpenRA.Game\Game.cs:line 798
   at OpenRA.Game.Run() in C:\Users\Public\Desktop\Games\Romanovs-Vengeance-master\game\engine\OpenRA.Game\Game.cs:line 836
   at OpenRA.Game.InitializeAndRun(String[] args) in C:\Users\Public\Desktop\Games\Romanovs-Vengeance-master\game\engine\OpenRA.Game\Game.cs:line 260
   at OpenRA.Program.Main(String[] args) in C:\Users\Public\Desktop\Games\Romanovs-Vengeance-master\game\engine\OpenRA.Game\Support\Program.cs:line 33

----------------------------------------
OpenRA has encountered a fatal error.
  * Log Files are available in Documents\OpenRA\Logs
  * FAQ is available at https://github.com/OpenRA/OpenRA/wiki/FAQ
----------------------------------------

I have attached my logs...
[Logs.zip](https://github.com/MustaphaTR/Romanovs-Vengeance/files/5005198/Logs.zip)

**Comment by GraionDilach** [comment] 2020-07-31 16:15
Do you have the replay? I've noticed this bug but so far unable to determinate the cause of it (The crashlog points to my code.)

**Comment by GraionDilach** [comment] 2020-08-01 15:02
Nevermind, this crash was fixed in my code. It'll hit the next build, I presume.

**Comment by MustaphaTR** [comment] 2020-08-02 11:13
Should be fixed by https://github.com/MustaphaTR/Romanovs-Vengeance/commit/da680952237622952cbe07b424148d576807506a

**Closed by MustaphaTR** 2020-08-02 11:13 UTC
