### ISSUE TITLE
Exception of type `System.NullReferenceException`: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Bond007s** [MustaphaTR/Romanovs-Vengeance#49] opened 2020-07-28 02:02 UTC
Here is the debug log from clients. This happens on skirmish and LAN game. It is running **build info** 
Platform is Windows
Engine version is 2e1c0b9
Using SDL 2 with OpenGL (Modern) renderer
Desktop resolution: 1400x1050
No custom resolution provided, using desktop resolution
Using resolution: 1400x1050
Using window scale 1.00
OpenGL version: 3.2.0
Using default sound device
Internal mods:
        rv: Red Alert 2: Romanov's Vengeance (2e1c0b9)
        all: All mods (2e1c0b9)
        cnc: Tiberian Dawn (2e1c0b9)
        d2k: Dune 2000 (2e1c0b9)
        modcontent: Mod Content Manager (2e1c0b9)
        ra: Red Alert (2e1c0b9)
        ts: Tiberian Sun (2e1c0b9)
External mods:
        cnc-release-20200503: Tiberian Dawn (release-20200503)
        d2k-release-20200503: Dune 2000 (release-20200503)
        example-20200202: Example mod (20200202)
        ra-release-20200503: Red Alert (release-20200503)
        sp-Release-20190623: Shattered Paradise (Release-20190623)
        dc-release-20200503: Dark Colony (release-20200503)
        rv-2e1c0b9: Red Alert 2: Romanov's Vengeance (2e1c0b9)
        sp-release-20200114: Shattered Paradise (release-20200114)
Loading mod: rv

**Here is the log at exception:**

Medium - GL Debug API Output: Performance - Program/shader state performance warning: Fragment Shader is going to be recompiled because the shader key based on GL state mismatches.
   at OpenRA.Platforms.Default.OpenGL.BuildErrorText(Int32 source, Int32 type, Int32 severity, StringBuilder message)
   at OpenRA.Platforms.Default.OpenGL.DebugMessageHandler(Int32 source, Int32 type, UInt32 id, Int32 severity, Int32 length, StringBuilder message, IntPtr userparam)
   at OpenRA.Platforms.Default.FrameBuffer.Bind()
   at OpenRA.Renderer.BeginUI()
   at OpenRA.Mods.Common.LoadScreens.SheetLoadScreen.Display()
   at OpenRA.Graphics.ChromeProvider.LoadCollection(String name, MiniYaml yaml)
   at OpenRA.Graphics.ChromeProvider.Initialize(ModData modData)
   at OpenRA.ModData.InitializeLoaders(IReadOnlyFileSystem fileSystem)
   at OpenRA.ModData.PrepareMap(String uid)
   at OpenRA.Game.StartGame(String mapUID, WorldType type)
   at OpenRA.Network.UnitOrders.ProcessOrder(OrderManager orderManager, World world, Int32 clientId, Order order)
   at OpenRA.Network.OrderManager.ProcessImmediateOrders()
   at OpenRA.Sync.<>c__DisplayClass13_0.<RunUnsynced>b__0()
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.Program.Main(String[] args)

Exception of type `System.NullReferenceException`: Object reference not set to an instance of an object.
   at OpenRA.Mods.AS.Projectiles.AthenaProjectile.Tick(World world) in C:\Users\Public\Desktop\Games\Romanovs-Vengeance-master\game\engine\OpenRA.Mods.AS\Projectiles\AthenaProjectile.cs:line 56
   at OpenRA.WorldUtils.DoTimed[T](IEnumerable`1 e, Action`1 a, String text) in C:\Users\Public\Desktop\Games\Romanovs-Vengeance-master\game\engine\OpenRA.Game\WorldUtils.cs:line 78
   at OpenRA.World.Tick() in C:\Users\Public\Desktop\Games\Romanovs-Vengeance-master\game\engine\OpenRA.Game\World.cs:line 468
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in C:\Users\Public\Desktop\Games\Romanovs-Vengeance-master\game\engine\OpenRA.Game\Game.cs:line 599
   at OpenRA.Game.LogicTick() in C:\Users\Public\Desktop\Games\Romanovs-Vengeance-master\game\engine\OpenRA.Game\Game.cs:line 626
   at OpenRA.Game.Loop() in C:\Users\Public\Desktop\Games\Romanovs-Vengeance-master\game\engine\OpenRA.Game\Game.cs:line 791
   at OpenRA.Game.Run() in C:\Users\Public\Desktop\Games\Romanovs-Vengeance-master\game\engine\OpenRA.Game\Game.cs:line 832
   at OpenRA.Game.InitializeAndRun(String[] args) in C:\Users\Public\Desktop\Games\Romanovs-Vengeance-master\game\engine\OpenRA.Game\Game.cs:line 262
   at OpenRA.Program.Main(String[] args) in C:\Users\Public\Desktop\Games\Romanovs-Vengeance-master\game\engine\OpenRA.Game\Support\Program.cs:line 33

----------------------------------------
OpenRA has encountered a fatal error.
  * Log Files are available in Documents\OpenRA\Logs
  * FAQ is available at https://github.com/OpenRA/OpenRA/wiki/FAQ
----------------------------------------
Press any key to continue . . .

**Comment by MustaphaTR** [comment] 2020-07-28 09:01
This is caused by Level 5 Generals' Powers and i'm currently working on the fix.

**Comment by MustaphaTR** [comment] 2020-07-29 13:01
I forgot to close this, should be fixed now.

**Closed by MustaphaTR** 2020-07-29 13:01 UTC
